#include <unistd.h>
#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#pragma comment(lib, "ws2_32.lib") // Link winsock lib

// stdlib
#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
#include <math.h> // isnan
#include <algorithm>
#include <cctype>

// system
#include <time.h>
#include <fcntl.h>

// C++
#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <map>

// proj
#include "common.h"
#include "hashtable.h"
#include "zset.h"
#include "list.h"
#include "heap.h"
#include "thread_pool.h"

typedef std::vector<uint8_t> Buffer;

// Forward declarations for response_begin and response_end
static void response_begin(Buffer &out, size_t *header);
static void response_end(Buffer &out, size_t header);


static void msg(const char *msg)
{
    fprintf(stderr, "%s\n", msg);
}

static void msg_errno(const char *msg)
{
    fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void die(const char *msg)
{
    fprintf(stderr, "[%d] %s\n", errno, msg);
    abort();
}

static uint64_t get_monotonic_msec()
{
    FILETIME ft;
    GetSystemTimeAsFileTime(&ft);
    uint64_t t = ((uint64_t)ft.dwHighDateTime << 32) | ft.dwLowDateTime;
    return (t - 116444736000000000ULL) / 10000; // Convert to milliseconds
}

static void fd_set_nb(SOCKET fd)
{
    u_long mode = 1;
    if (ioctlsocket(fd, FIONBIO, &mode) != 0)
    {
        die("ioctlsocket error");
    }
}

const size_t k_max_msg = 32 << 20; // likely larger than the kernel buffer


// append to the back
static void buf_append(Buffer &buf, const uint8_t *data, size_t len)
{
    buf.insert(buf.end(), data, data + len);
}
// remove from the front
static void buf_consume(Buffer &buf, size_t n)
{
    buf.erase(buf.begin(), buf.begin() + n);
}

struct Conn
{
    SOCKET fd = INVALID_SOCKET;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    Buffer incoming; // data to be parsed by the application
    Buffer outgoing; // responses generated by the application
    // timer
    uint64_t last_active_ms = 0;
    DList idle_node;

    //pub-sub model
    bool is_subscribed = false;
    std::vector<std::string> subscribed_channels;
};

// global states
static struct
{
    HMap db;
    // a map of all client connections, keyed by fd
    std::vector<Conn *> fd2conn;
    // timers for idle connections
    DList idle_list;
    // timers for TTLs
    std::vector<HeapItem> heap;
    // the thread pool
    TheadPool thread_pool;
    // server shutdown flag
    bool shutdown_requested = false;

    std::map<std::string, std::vector<Conn *>> pubsub_channels;
} g_data;

// application callback when the listening socket is ready
static int32_t handle_accept(SOCKET fd)
{
    // accept
    struct sockaddr_in client_addr = {};
    int addrlen = sizeof(client_addr);
    SOCKET connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);
    if (connfd == INVALID_SOCKET)
    {
        msg_errno("accept() error");
        return -1;
    }
    uint32_t ip = client_addr.sin_addr.s_addr;
    fprintf(stderr, "new client from %u.%u.%u.%u:%u\n",
            ip & 255, (ip >> 8) & 255, (ip >> 16) & 255, ip >> 24,
            ntohs(client_addr.sin_port));

    // set the new connection fd to nonblocking mode
    fd_set_nb(connfd);

    // create a `struct Conn`
    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true;
    conn->last_active_ms = get_monotonic_msec();
    dlist_insert_before(&g_data.idle_list, &conn->idle_node);

    // put it into the map
    if (g_data.fd2conn.size() <= (size_t)conn->fd)
    {
        g_data.fd2conn.resize(conn->fd + 1);
    }
    assert(!g_data.fd2conn[conn->fd]);
    g_data.fd2conn[conn->fd] = conn;

    return 0;
}

static void conn_destroy(Conn *conn)
{

    if (conn->is_subscribed) {
        for (const std::string& channel_name : conn->subscribed_channels) {
            auto it = g_data.pubsub_channels.find(channel_name);
            if (it != g_data.pubsub_channels.end()) {
                std::vector<Conn*>& subscribers = it->second;
                // Remove the connection pointer from the vector.
                auto to_remove = std::remove(subscribers.begin(), subscribers.end(), conn);
                subscribers.erase(to_remove, subscribers.end());

                // If no subscribers are left, remove the channel itself to save memory.
                if (subscribers.empty()) {
                    g_data.pubsub_channels.erase(it);
                }
            }
        }
    }

    closesocket(conn->fd);
    g_data.fd2conn[conn->fd] = NULL;
    dlist_detach(&conn->idle_node);
    delete conn;
}

const size_t k_max_args = 200 * 1000;

static bool read_u32(const uint8_t *&cur, const uint8_t *end, uint32_t &out)
{
    if (cur + 4 > end)
    {
        return false;
    }
    memcpy(&out, cur, 4);
    cur += 4;
    return true;
}

static bool
read_str(const uint8_t *&cur, const uint8_t *end, size_t n, std::string &out)
{
    if (cur + n > end)
    {
        return false;
    }
    out.assign(cur, cur + n);
    cur += n;
    return true;
}

// ------------------------------------------------------------
// | nstr | len | str1 | len | str2 | ... | len | strn |
// ------------------------------------------------------------

static int32_t
parse_req(const uint8_t *data, size_t size, std::vector<std::string> &out)
{
    const uint8_t *end = data + size;
    uint32_t nstr = 0;
    if (!read_u32(data, end, nstr))
    {
        return -1;
    }
    if (nstr > k_max_args)
    {
        return -1; // safety limit
    }

    while (out.size() < nstr)
    {
        uint32_t len = 0;
        if (!read_u32(data, end, len))
        {
            return -1;
        }
        out.push_back(std::string());
        if (!read_str(data, end, len, out.back()))
        {
            return -1;
        }
    }
    if (data != end)
    {
        return -1; // trailing garbage
    }
    return 0;
}

// error code for TAG_ERR
enum
{
    ERR_UNKNOWN = 1, // unknown command
    ERR_TOO_BIG = 2, // response too big
    ERR_BAD_TYP = 3, // unexpected value type
    ERR_BAD_ARG = 4, // bad arguments
};

// data types of serialized data
enum
{
    TAG_NIL = 0, // nil
    TAG_ERR = 1, // error code + msg
    TAG_STR = 2, // string
    TAG_INT = 3, // int64
    TAG_DBL = 4, // double
    TAG_ARR = 5, // array
};

// help functions for the serialization
static void buf_append_u8(Buffer &buf, uint8_t data)
{
    buf_append(buf, &data, 1);
}
static void buf_append_u32(Buffer &buf, uint32_t data)
{
    buf_append(buf, (const uint8_t *)&data, 4);
}
static void buf_append_i64(Buffer &buf, int64_t data)
{
    buf_append(buf, (const uint8_t *)&data, 8);
}
static void buf_append_dbl(Buffer &buf, double data)
{
    buf_append(buf, (const uint8_t *)&data, 8);
}

// append serialized data types to the back
static void out_nil(Buffer &out)
{
    buf_append_u8(out, TAG_NIL);
}
static void out_str(Buffer &out, const char *s, size_t size)
{
    buf_append_u8(out, TAG_STR);
    buf_append_u32(out, (uint32_t)size);
    buf_append(out, (const uint8_t *)s, size);
}
static void out_int(Buffer &out, int64_t val)
{
    buf_append_u8(out, TAG_INT);
    buf_append_i64(out, val);
}
static void out_dbl(Buffer &out, double val)
{
    buf_append_u8(out, TAG_DBL);
    buf_append_dbl(out, val);
}
static void out_err(Buffer &out, uint32_t code, const std::string &msg)
{
    buf_append_u8(out, TAG_ERR);
    buf_append_u32(out, code);
    buf_append_u32(out, (uint32_t)msg.size());
    buf_append(out, (const uint8_t *)msg.data(), msg.size());
}
static void out_arr(Buffer &out, uint32_t n)
{
    buf_append_u8(out, TAG_ARR);
    buf_append_u32(out, n);
}
static size_t out_begin_arr(Buffer &out)
{
    out.push_back(TAG_ARR);
    buf_append_u32(out, 0); // filled by out_end_arr()
    return out.size() - 4;  // the `ctx` arg
}
static void out_end_arr(Buffer &out, size_t ctx, uint32_t n)
{
    assert(out[ctx - 1] == TAG_ARR);
    memcpy(&out[ctx], &n, 4);
}

// value types
enum
{
    T_INIT = 0,
    T_STR = 1,  // string
    T_ZSET = 2, // sorted set
};

// KV pair for the top-level hashtable
struct Entry
{
    struct HNode node; // hashtable node
    std::string key;
    // for TTL
    size_t heap_idx = -1; // array index to the heap item
    // value
    uint32_t type = 0;
    // one of the following
    std::string str;
    ZSet zset;
};

static Entry *entry_new(uint32_t type)
{
    Entry *ent = new Entry();
    ent->type = type;
    return ent;
}

static void entry_set_ttl(Entry *ent, int64_t ttl_ms);

static void entry_del_sync(Entry *ent)
{
    if (ent->type == T_ZSET)
    {
        zset_clear(&ent->zset);
    }
    delete ent;
}

static void entry_del_func(void *arg)
{
    entry_del_sync((Entry *)arg);
}

static void entry_del(Entry *ent)
{
    // unlink it from any data structures
    entry_set_ttl(ent, -1); // remove from the heap data structure
    // run the destructor in a thread pool for large data structures
    size_t set_size = (ent->type == T_ZSET) ? hm_size(&ent->zset.hmap) : 0;
    const size_t k_large_container_size = 1000;
    if (set_size > k_large_container_size)
    {
        thread_pool_queue(&g_data.thread_pool, &entry_del_func, ent);
    }
    else
    {
        entry_del_sync(ent); // small; avoid context switches
    }
}

struct LookupKey
{
    struct HNode node; // hashtable node
    std::string key;
};

// equality comparison for the top-level hashstable
static bool entry_eq(HNode *node, HNode *key)
{
    struct Entry *ent = container_of(node, struct Entry, node);
    struct LookupKey *keydata = container_of(key, struct LookupKey, node);
    return ent->key == keydata->key;
}

static void do_get(std::vector<std::string> &cmd, Buffer &out)
{


    std::string curr_key = "";

    std::string str = ""; 

    for(int i=1;i<cmd.size();i++){
        str += cmd[i] + " "; 
    }
    str.pop_back();

    if(str[0] == '"'){
        auto pos = str.find('"', 1);
        if(pos != std::string::npos && pos == str.size() - 1) {
            curr_key = str.substr(1, pos - 1);
        } else {
            std::cout << "pos: err1 " << pos << std::endl;
            return out_err(out, ERR_BAD_ARG, "expect quoted string");
        }
    }
    else{
        if(str.size() > 1 ){
            
            return out_err(out, ERR_BAD_ARG, "expect quoted string");
        }
        curr_key = str.substr(0, str.find(' '));
    }
    if(curr_key.empty()){
        return out_err(out, ERR_BAD_ARG, "expect quoted string");
    }

    std::cout << "curr_key: " << curr_key << std::endl;

    // a dummy struct just for the lookup
    LookupKey key;
    key.key = curr_key;
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    // hashtable lookup
    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!node)
    {
        return out_nil(out);
    }
    // copy the value
    Entry *ent = container_of(node, Entry, node);
    if (ent->type != T_STR)
    {
        return out_err(out, ERR_BAD_TYP, "not a string value");
    }
    return out_str(out, ent->str.data(), ent->str.size());
}

static void do_set(std::vector<std::string> &cmd, Buffer &out)
{

    
    if(cmd.size() < 3){
        return out_err(out, ERR_BAD_ARG, "missing value to set");
    }

    // a dummy struct just for the lookup
    std::string str = ""; 

    for(int i=1;i<cmd.size();i++){
        str += cmd[i] + " "; 
    }
    str.pop_back();

    std::string curr_key = "";
    std::string curr_val = "";
    std::string tmp_val;

   if(str[0] == '"'){
        auto pos = str.find('"', 1);
        if(pos != std::string::npos || str[pos + 1] == ' ') {
            curr_key = str.substr(1, pos - 1);

            size_t next_space = str.find_first_not_of(' ', pos + 1);
            if (next_space != std::string::npos) {
                tmp_val = str.substr(next_space);
            } else {
               return out_err(out, ERR_BAD_ARG, "expect quoted string");
            }
            std::cout<<"curr_key:" << curr_key << std::endl;
            std::cout<<"tmp_val:" << tmp_val << std::endl;
        } else {
            return out_err(out, ERR_BAD_ARG, "expect quoted string");
        }
   }
   else{
    curr_key = str.substr(0, str.find(' '));
    tmp_val = str.substr(str.find(' ') + 1);
}
    if(tmp_val[0] == '"'){
        auto pos = tmp_val.find('"', 1);
        if(pos == tmp_val.size()-1) {
            curr_val = tmp_val.substr(1, pos - 1);
        } else {
            return out_err(out, ERR_BAD_ARG, "expect quoted string");
        }
    }
    else{
        std::cout << tmp_val.find(' ',1) << std::endl;
        std::cout << tmp_val << std::endl;
        if(tmp_val.find(' ',1) == std::string::npos){
            curr_val = tmp_val.substr(0, tmp_val.find(' '));
            std::cout<<"code ni "<<std::endl;
            std::cout << "curr_val: " << curr_val << std::endl;
        }
        else{
            return out_err(out, ERR_BAD_ARG, "syntax error, expect quoted string");
        }
    }
    if(curr_key.empty() || curr_val.empty()){
        return out_err(out, ERR_BAD_ARG, "expect quoted string");
    }

    std::cout<<curr_key<<std::endl;
    std::cout<<curr_val<<std::endl;

    LookupKey key;
    key.key = curr_key;
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());

    // hashtable lookup
    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (node)
    {
        // found, update the value
        Entry *ent = container_of(node, Entry, node);
        if (ent->type != T_STR)
        {
            return out_err(out, ERR_BAD_TYP, "a non-string value exists");
        }
        std::string quoted = curr_val;
        ent->str.swap(quoted);
    }
    else
    {
        // not found, allocate & insert a new pair
        Entry *ent = entry_new(T_STR);
        ent->key = key.key;
        ent->node.hcode = key.node.hcode;
        std::string quoted = curr_val;
        ent->str.swap(quoted);
        hm_insert(&g_data.db, &ent->node);
    }
    return out_nil(out);
}

// Helper to remove outer quotes if present
static std::string strip_quotes(const std::string& s) {
    if (s.size() >= 2 && s.front() == '"' && s.back() == '"') {
        return s.substr(1, s.size() - 2);
    }
    return s;
}

static void do_append(std::vector<std::string> &cmd, Buffer &out)
{

    
    if(cmd.size() < 3){
        return out_err(out, ERR_BAD_ARG, "missing value to set");
    }

    // a dummy struct just for the lookup
    std::string str = ""; 

    for(int i=1;i<cmd.size();i++){
        str += cmd[i] + " "; 
    }
    str.pop_back();

    std::string curr_key = "";
    std::string curr_val = "";
    std::string tmp_val;

   if(str[0] == '"'){
        auto pos = str.find('"', 1);
        if(pos != std::string::npos || str[pos + 1] == ' ') {
            curr_key = str.substr(1, pos - 1);

            size_t next_space = str.find_first_not_of(' ', pos + 1);
            if (next_space != std::string::npos) {
                tmp_val = str.substr(next_space);
            } else {
               return out_err(out, ERR_BAD_ARG, "expect quoted string");
            }
            std::cout<<"curr_key:" << curr_key << std::endl;
            std::cout<<"tmp_val:" << tmp_val << std::endl;
        } else {
            return out_err(out, ERR_BAD_ARG, "expect quoted string");
        }
   }
   else{
    curr_key = str.substr(0, str.find(' '));
    tmp_val = str.substr(str.find(' ') + 1);
}
    if(tmp_val[0] == '"'){
        auto pos = tmp_val.find('"', 1);
        if(pos == tmp_val.size()-1) {
            curr_val = tmp_val.substr(1, pos - 1);
        } else {
            return out_err(out, ERR_BAD_ARG, "expect quoted string");
        }
    }
    else{
        std::cout << tmp_val.find(' ',1) << std::endl;
        std::cout << tmp_val << std::endl;
        if(tmp_val.find(' ',1) == std::string::npos){
            curr_val = tmp_val.substr(0, tmp_val.find(' '));
            std::cout<<"code ni "<<std::endl;
            std::cout << "curr_val: " << curr_val << std::endl;
        }
        else{
            return out_err(out, ERR_BAD_ARG, "syntax error, expect quoted string");
        }
    }
    if(curr_key.empty() || curr_val.empty()){
        return out_err(out, ERR_BAD_ARG, "expect quoted string");
    }

    std::cout<<curr_key<<std::endl;
   
    // hashtable lookup
    LookupKey key;
    key.key = curr_key;
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (node)
    {
        // found, update the value
        Entry *ent = container_of(node, Entry, node);
        if (ent->type != T_STR)
        {
            return out_err(out, ERR_BAD_TYP, "a non-string value exists");
        }
        // Remove quotes from existing value and new value, then concatenate and re-wrap
        std::string existing = strip_quotes(ent->str);
        std::string to_append = strip_quotes(str);
        ent->str = "\"" + existing + curr_val + "\"";
    }
    else
    {
        // not found, allocate & insert a new pair
        std::string to_append = strip_quotes(str);
        Entry *ent = entry_new(T_STR);
        ent->key = key.key;
        ent->node.hcode = key.node.hcode;
        ent->str = "\"" + curr_val + "\"";
        hm_insert(&g_data.db, &ent->node);
    }
    return out_nil(out);
}

static void do_decr(std::vector<std::string> &cmd, Buffer &out){
    LookupKey key;
    key.key = cmd[1];
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());

    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);

    if(node){
        Entry *ent = container_of(node, Entry, node);

        if (ent->type != T_STR)
        {
            return out_err(out, ERR_BAD_TYP, "WRONGTYPE Operation against a key holding the wrong kind of value");
        }
        std::cout<<ent->str[0]<<std::endl;
        if(ent->str[1]=='0'){
            std::cout << "value is not an integer or out of range" << std::endl;
            return out_err(out, ERR_BAD_ARG, "value is not an integer or out of range");
        }
        // Convert the string to an integer
        int64_t value = std::stoll(strip_quotes(ent->str));
        // Decrement the value
        value--;
        // Update the entry with the new value
        ent->str = "\"" + std::to_string(value) + "\"";
        // Return the new value
        return out_int(out, value);
    }
    // If the key does not exist, create it with a value of -1
    Entry *ent = entry_new(T_STR);
    ent->key = key.key;
    ent->node.hcode = key.node.hcode;
    ent->str = "\"-1\""; // Initialize with -1
    hm_insert(&g_data.db, &ent->node);
    // Return -1 as the new value
    return out_int(out, -1);

}

static void do_del(std::vector<std::string> &cmd, Buffer &out)
{
    // a dummy struct just for the lookup
    LookupKey key;
    key.key = cmd[1];
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    // hashtable delete
    HNode *node = hm_delete(&g_data.db, &key.node, &entry_eq);
    if (node)
    { // deallocate the pair
        entry_del(container_of(node, Entry, node));
    }
    return out_int(out, node ? 1 : 0);
}

static void do_subscribe(Conn *conn, std::vector<std::string> &cmd, Buffer &out) {
    conn->is_subscribed = true; // Set the client to subscriber mode.

    // A client can subscribe to multiple channels at once, e.g., SUBSCRIBE news sports
    for (size_t i = 1; i < cmd.size(); ++i) {
        const std::string &channel_name = cmd[i];
        
        // Add the connection to the channel's list of subscribers.
        g_data.pubsub_channels[channel_name].push_back(conn);
        // Record the subscription on the connection itself for later cleanup.
        conn->subscribed_channels.push_back(channel_name);

        // Respond to the client confirming the subscription, as per Redis protocol.
        // The response is an array: ["subscribe", "channel_name", subscription_count]
        out_arr(out, 3);
        out_str(out, "subscribe", 9);
        out_str(out, channel_name.data(), channel_name.size());
        out_int(out, (int64_t)conn->subscribed_channels.size());
    }
    std::cout << "SUBSCRIBE: Client subscribed to " << conn->subscribed_channels.size() 
              << " channels." << std::endl;
    // Set the connection to want_write to ensure the response is sent.
    
}

// Handles the `PUBLISH` command.
static void do_publish(std::vector<std::string> &cmd, Buffer &out) {
    const std::string &channel_name = cmd[1];

    std::string message = cmd[2];
    for (size_t i = 3; i < cmd.size(); ++i) {
        message += " " + cmd[i];
    }


    int receivers = 0;

    // Find the list of subscribers for the given channel.
    auto it = g_data.pubsub_channels.find(channel_name);
    if (it != g_data.pubsub_channels.end()) {
        // Prepare the message that will be sent to all subscribers.
        // Format: ["message", "channel_name", "the_message"]
        std::cout << "PUBLISH: " << channel_name << " with message: " << message << std::endl;
        Buffer pub_message;
        size_t header_pos = 0;
        response_begin(pub_message, &header_pos); // Prepares the 4-byte length header
        out_arr(pub_message, 3);
        out_str(pub_message, "message", 7);
        out_str(pub_message, channel_name.data(), channel_name.size());
        out_str(pub_message, message.data(), message.size());
        response_end(pub_message, header_pos); // Fills in the correct length

        // Send the message to each subscriber.
        for (Conn *sub_conn : it->second) {
            buf_append(sub_conn->outgoing, pub_message.data(), pub_message.size());
            sub_conn->want_write = true; // Tell the event loop to send the data.
            receivers++;
        }
    }
    // std::cout << "PUBLISH: " << channel_name << " to " << receivers << " subscribers." << std::endl;
    // std::cout << "Message: " << message << std::endl;
    
    //print out
    std::cout<<"out"<<std::endl;
    for(auto x:out){
        std::cout << x;
    }
    std::cout << std::endl;

    // Respond to the publisher with the number of clients that received the message.
    return out_int(out, receivers);
}

static void heap_delete(std::vector<HeapItem> &a, size_t pos)
{
    // swap the erased item with the last item
    a[pos] = a.back();
    a.pop_back();
    // update the swapped item
    if (pos < a.size())
    {
        heap_update(a.data(), pos, a.size());
    }
}

static void heap_upsert(std::vector<HeapItem> &a, size_t pos, HeapItem t)
{
    if (pos < a.size())
    {
        a[pos] = t; // update an existing item
    }
    else
    {
        pos = a.size();
        a.push_back(t); // or add a new item
    }
    heap_update(a.data(), pos, a.size());
}

// set or remove the TTL
static void entry_set_ttl(Entry *ent, int64_t ttl_ms)
{
    if (ttl_ms < 0 && ent->heap_idx != (size_t)-1)
    {
        // setting a negative TTL means removing the TTL
        heap_delete(g_data.heap, ent->heap_idx);
        ent->heap_idx = -1;
    }
    else if (ttl_ms >= 0)
    {
        // add or update the heap data structure
        uint64_t expire_at = get_monotonic_msec() + (uint64_t)ttl_ms;
        HeapItem item;
        item.val = expire_at;
        item.ref = &ent->heap_idx;
        heap_upsert(g_data.heap, ent->heap_idx, item);
    }
}

static bool str2int(const std::string &s, int64_t &out)
{
    char *endp = NULL;
    out = strtoll(s.c_str(), &endp, 10);
    return endp == s.c_str() + s.size();
}

// PEXPIRE key ttl_ms
static void do_expire(std::vector<std::string> &cmd, Buffer &out)
{
    int64_t ttl_ms = 0;
    if (!str2int(cmd[2], ttl_ms))
    {
        return out_err(out, ERR_BAD_ARG, "expect int64");
    }

    LookupKey key;
    key.key = cmd[1];
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());

    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (node)
    {
        Entry *ent = container_of(node, Entry, node);
        entry_set_ttl(ent, ttl_ms);
    }
    return out_int(out, node ? 1 : 0);
}

// PTTL key
static void do_ttl(std::vector<std::string> &cmd, Buffer &out)
{
    LookupKey key;
    key.key = cmd[1];
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());

    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!node)
    {
        return out_int(out, -2); // not found
    }

    Entry *ent = container_of(node, Entry, node);
    if (ent->heap_idx == (size_t)-1)
    {
        return out_int(out, -1); // no TTL
    }

    uint64_t expire_at = g_data.heap[ent->heap_idx].val;
    uint64_t now_ms = get_monotonic_msec();
    return out_int(out, expire_at > now_ms ? (expire_at - now_ms) : 0);
}

// Pattern matching structure for keys command
struct KeysPattern
{
    std::string pattern;
    Buffer &out;
    uint32_t count = 0;
};

// Simple wildcard pattern matching
static bool pattern_match(const std::string &text, const std::string &pattern)
{
    size_t text_pos = 0, pattern_pos = 0;
    size_t text_len = text.length(), pattern_len = pattern.length();

    while (pattern_pos < pattern_len)
    {
        if (pattern[pattern_pos] == '*')
        {
            // Handle wildcard
            pattern_pos++;
            if (pattern_pos >= pattern_len)
            {
                return true; // * at end matches everything
            }

            // Find next occurrence of pattern after *
            bool found = false;
            for (size_t i = text_pos; i < text_len; i++)
            {
                if (pattern_match(text.substr(i), pattern.substr(pattern_pos)))
                {
                    found = true;
                    break;
                }
            }
            return found;
        }
        else if (text_pos < text_len && (pattern[pattern_pos] == '?' || pattern[pattern_pos] == text[text_pos]))
        {
            // Handle single character match or exact match
            text_pos++;
            pattern_pos++;
        }
        else
        {
            return false;
        }
    }

    return text_pos >= text_len;
}

// Callback for counting keys
static bool cb_count_keys(HNode *node, void *arg)
{
    KeysPattern *keys_data = (KeysPattern *)arg;
    const std::string &key = container_of(node, Entry, node)->key;

    // If no pattern or pattern matches, count the key
    if (keys_data->pattern.empty() || pattern_match(key, keys_data->pattern))
    {
        keys_data->count++;
    }
    return true;
}

// Callback for collecting keys
static bool cb_collect_keys(HNode *node, void *arg)
{
    KeysPattern *keys_data = (KeysPattern *)arg;
    const std::string &key = container_of(node, Entry, node)->key;

    // If no pattern or pattern matches, add the key
    if (keys_data->pattern.empty() || pattern_match(key, keys_data->pattern))
    {
        out_str(keys_data->out, key.data(), key.size());
        keys_data->count++;
    }
    return true;
}

static void do_keys(std::vector<std::string> &cmd, Buffer &out)
{
    std::string pattern;
    if (cmd.size() > 1)
    {
        pattern = cmd[1];
    }

    // If no pattern, return all keys
    if (pattern.empty())
    {
        size_t total_keys = hm_size(&g_data.db);
        out_arr(out, total_keys);
        hm_foreach(&g_data.db, [](HNode *node, void *arg) -> bool
                   {
            Buffer &out = *(Buffer *)arg;
            const std::string &key = container_of(node, Entry, node)->key;
            out_str(out, key.data(), key.size());
            return true; }, (void *)&out);
        return;
    }

    // If pattern, return only matching keys
    // First pass: count
    size_t match_count = 0;
    struct CountCtx
    {
        std::string *pattern;
        size_t *count;
    } count_ctx = {&pattern, &match_count};
    hm_foreach(&g_data.db, [](HNode *node, void *arg) -> bool
               {
        CountCtx *ctx = (CountCtx *)arg;
        const std::string &key = container_of(node, Entry, node)->key;
        if (pattern_match(key, *ctx->pattern)) (*ctx->count)++;
        return true; }, &count_ctx);

    out_arr(out, match_count);
    // Second pass: collect
    struct CollectCtx
    {
        std::string *pattern;
        Buffer *out;
    } collect_ctx = {&pattern, &out};
    hm_foreach(&g_data.db, [](HNode *node, void *arg) -> bool
               {
        CollectCtx *ctx = (CollectCtx *)arg;
        const std::string &key = container_of(node, Entry, node)->key;
        if (pattern_match(key, *ctx->pattern)) out_str(*ctx->out, key.data(), key.size());
        return true; }, &collect_ctx);
}

// SHUTDOWN command
static void do_shutdown(std::vector<std::string> &cmd, Buffer &out)
{
    out_str(out, "Server shutting down...", 22);
    g_data.shutdown_requested = true;
    // Force immediate shutdown
    exit(0);
}

static bool str2dbl(const std::string &s, double &out)
{
    char *endp = NULL;
    out = strtod(s.c_str(), &endp);
    return endp == s.c_str() + s.size() && !isnan(out);
}

// zadd zset score name
static void do_zadd(std::vector<std::string> &cmd, Buffer &out)
{
    double score = 0;
    if (!str2dbl(cmd[2], score))
    {
        return out_err(out, ERR_BAD_ARG, "expect float");
    }

    // look up or create the zset
    LookupKey key;
    key.key = cmd[1];
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);

    Entry *ent = NULL;
    if (!hnode)
    { // insert a new key
        ent = entry_new(T_ZSET);
        ent->key = key.key;
        ent->node.hcode = key.node.hcode;
        hm_insert(&g_data.db, &ent->node);
    }
    else
    { // check the existing key
        ent = container_of(hnode, Entry, node);
        if (ent->type != T_ZSET)
        {
            return out_err(out, ERR_BAD_TYP, "expect zset");
        }
    }

    // add or update the tuple
    const std::string &name = cmd[3];
    bool added = zset_insert(&ent->zset, name.data(), name.size(), score);
    return out_int(out, (int64_t)added);
}

static const ZSet k_empty_zset;

static ZSet *expect_zset(std::string &s)
{
    LookupKey key;
    key.key = s;
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!hnode)
    { // a non-existent key is treated as an empty zset
        return (ZSet *)&k_empty_zset;
    }
    Entry *ent = container_of(hnode, Entry, node);
    return ent->type == T_ZSET ? &ent->zset : NULL;
}

// zrem zset name
static void do_zrem(std::vector<std::string> &cmd, Buffer &out)
{
    ZSet *zset = expect_zset(cmd[1]);
    if (!zset)
    {
        return out_err(out, ERR_BAD_TYP, "expect zset");
    }

    const std::string &name = cmd[2];
    ZNode *znode = zset_lookup(zset, name.data(), name.size());
    if (znode)
    {
        zset_delete(zset, znode);
    }
    return out_int(out, znode ? 1 : 0);
}

// zscore zset name
static void do_zscore(std::vector<std::string> &cmd, Buffer &out)
{
    ZSet *zset = expect_zset(cmd[1]);
    if (!zset)
    {
        return out_err(out, ERR_BAD_TYP, "expect zset");
    }

    const std::string &name = cmd[2];
    ZNode *znode = zset_lookup(zset, name.data(), name.size());
    return znode ? out_dbl(out, znode->score) : out_nil(out);
}

// zquery zset score name offset limit
static void do_zquery(std::vector<std::string> &cmd, Buffer &out)
{
    // parse args
    double score = 0;
    if (!str2dbl(cmd[2], score))
    {
        return out_err(out, ERR_BAD_ARG, "expect fp number");
    }
    const std::string &name = cmd[3];
    int64_t offset = 0, limit = 0;
    if (!str2int(cmd[4], offset) || !str2int(cmd[5], limit))
    {
        return out_err(out, ERR_BAD_ARG, "expect int");
    }

    // get the zset
    ZSet *zset = expect_zset(cmd[1]);
    if (!zset)
    {
        return out_err(out, ERR_BAD_TYP, "expect zset");
    }

    // seek to the key
    if (limit <= 0)
    {
        return out_arr(out, 0);
    }
    ZNode *znode = zset_seekge(zset, score, name.data(), name.size());
    znode = znode_offset(znode, offset);

    // output
    size_t ctx = out_begin_arr(out);
    int64_t n = 0;
    while (znode && n < limit)
    {
        out_str(out, znode->name, znode->len);
        out_dbl(out, znode->score);
        znode = znode_offset(znode, +1);
        n += 2;
    }
    out_end_arr(out, ctx, (uint32_t)n);
}

static void do_request(Conn *conn , std::vector<std::string> &cmd, Buffer &out)
{
    std::string str = cmd[0];
    std::transform(str.begin(), str.end(), str.begin(), ::tolower);

    if (conn->is_subscribed) {
        // If subscribed, only allow SUBSCRIBE/UNSUBSCRIBE
        if (str == "subscribe") {
            return do_subscribe(conn, cmd, out);
        } else {
            return out_err(out, ERR_BAD_ARG, "Cannot use command in subscriber mode");
        }
    }


    if (cmd.size() >= 2 && str == "get")
    {
        return do_get(cmd, out);
    }
    else if (cmd.size() >= 3 && str == "set")
    {
        return do_set(cmd, out);
    }
    else if (cmd.size() == 2 && str == "del")
    {
        return do_del(cmd, out);
    }
    else if (cmd.size() >= 3 && str == "append")
    {
        return do_append(cmd, out);
    }
    else if(cmd.size() ==2 && str == "decr"){
        return do_decr(cmd,out);
    }
    else if (cmd.size() == 3 && str == "pexpire")
    {
        return do_expire(cmd, out);
    }
    else if (cmd.size() == 2 && str == "pttl")
    {
        return do_ttl(cmd, out);
    }
    else if ((cmd.size() == 1 || cmd.size() == 2) && str == "keys")
    {
        return do_keys(cmd, out);
    }
    else if (cmd.size() == 4 && str == "zadd")
    {
        return do_zadd(cmd, out);
    }
    else if (cmd.size() == 3 && str == "zrem")
    {
        return do_zrem(cmd, out);
    }
    else if (cmd.size() == 3 && str == "zscore")
    {
        return do_zscore(cmd, out);
    }
    else if (cmd.size() == 6 && str == "zquery")
    {
        return do_zquery(cmd, out);
    }
    else if (cmd.size() == 1 && str == "shutdown")
    {
        return do_shutdown(cmd, out);
    }
    else if (str == "subscribe" && cmd.size() >= 2) {
        return do_subscribe(conn, cmd, out);
    } else if (str == "publish" && cmd.size() >= 3) { // Use >= 3
        return do_publish(cmd, out);
    }
    else
    {
        return out_err(out, ERR_UNKNOWN, "unknown command.");
    }
}

static void response_begin(Buffer &out, size_t *header)
{
    *header = out.size();   // messege header position
    buf_append_u32(out, 0); // reserve space
}
static size_t response_size(Buffer &out, size_t header)
{
    return out.size() - header - 4;
}
static void response_end(Buffer &out, size_t header)
{
    size_t msg_size = response_size(out, header);
    if (msg_size > k_max_msg)
    {
        out.resize(header + 4);
        out_err(out, ERR_TOO_BIG, "response is too big.");
        msg_size = response_size(out, header);
    }
    // message header
    uint32_t len = (uint32_t)msg_size;
    memcpy(&out[header], &len, 4);
}

// process 1 request if there is enough data
static bool try_one_request(Conn *conn)
{
    // try to parse the protocol: message header
    if (conn->incoming.size() < 4)
    {
        return false; // want read
    }
    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);
    if (len > k_max_msg)
    {
        msg("too long");
        conn->want_close = true;
        return false; // want close
    }
    // message body
    if (4 + len > conn->incoming.size())
    {
        return false; // want read
    }
    const uint8_t *request = &conn->incoming[4];

    // got one request, do some application logic
    std::vector<std::string> cmd;
    if (parse_req(request, len, cmd) < 0)
    {
        msg("bad request");
        conn->want_close = true;
        return false; // want close
    }

   Buffer response_part;
   do_request(conn, cmd, response_part);

   

// Package the response and add it to the outgoing buffer.
if (response_part.size() > 0) {
    size_t header_pos = 0;
    response_begin(conn->outgoing, &header_pos);
    buf_append(conn->outgoing, response_part.data(), response_part.size());
    response_end(conn->outgoing, header_pos);
}


    // application logic done! remove the request message.
    buf_consume(conn->incoming, 4 + len);

   

    // Q: Why not just empty the buffer? See the explanation of "pipelining".
    return true; // success
}

// application callback when the socket is writable
static void handle_write(Conn *conn)
{
    assert(conn->outgoing.size() > 0);
    int rv = send(conn->fd, (const char *)&conn->outgoing[0], (int)conn->outgoing.size(), 0);
    if (rv < 0 && WSAGetLastError() == WSAEWOULDBLOCK)
    {
        return; // actually not ready
    }
    if (rv < 0)
    {
        msg_errno("send() error");
        conn->want_close = true; // error handling
        return;
    }

    // remove written data from `outgoing`
    buf_consume(conn->outgoing, (size_t)rv);
    std::cout << "Sending data to subscriber: " << conn->fd << ", size: " << conn->outgoing.size() << std::endl;

    // update the readiness intention
    if (conn->outgoing.size() == 0)
    { // all data written
        conn->want_read = true;
        conn->want_write = false;
    } // else: want write
  
}

// application callback when the socket is readable
static void handle_read(Conn *conn)
{
    // read some data
    uint8_t buf[64 * 1024];
    int rv = recv(conn->fd, (char *)buf, sizeof(buf), 0);
    if (rv < 0 && WSAGetLastError() == WSAEWOULDBLOCK)
    {
        return; // actually not ready
    }
    // handle IO error
    if (rv < 0)
    {
        msg_errno("recv() error");
        conn->want_close = true;
        return; // want close
    }
    // handle EOF
    if (rv == 0)
    {
        if (conn->incoming.size() == 0)
        {
            msg("client closed");
        }
        else
        {
            msg("unexpected EOF");
        }
        conn->want_close = true;
        return; // want close
    }
    // got some new data
    buf_append(conn->incoming, buf, (size_t)rv);

    // parse requests and generate responses
    while (try_one_request(conn))
    {
    }
    // Q: Why calling this in a loop? See the explanation of "pipelining".

    // update the readiness intention
    if (conn->outgoing.size() > 0)
    { // has a response
        conn->want_read = false;
        conn->want_write = true;
        // The socket is likely ready to write in a request-response protocol,
        // try to write it without waiting for the next iteration.
        return handle_write(conn);
    } // else: want read
}

const uint64_t k_idle_timeout_ms = 5 * 1000;

static uint32_t next_timer_ms()
{
    uint64_t now_ms = get_monotonic_msec();
    uint64_t next_ms = (uint64_t)-1;
    // idle timers using a linked list
    if (!dlist_empty(&g_data.idle_list))
    {
        Conn *conn = container_of(g_data.idle_list.next, Conn, idle_node);
        next_ms = conn->last_active_ms + k_idle_timeout_ms;
    }
    // TTL timers using a heap
    if (!g_data.heap.empty() && g_data.heap[0].val < next_ms)
    {
        next_ms = g_data.heap[0].val;
    }
    // timeout value
    if (next_ms == (uint64_t)-1)
    {
        return -1; // no timers, no timeouts
    }
    if (next_ms <= now_ms)
    {
        return 0; // missed?
    }
    return (int32_t)(next_ms - now_ms);
}

static bool hnode_same(HNode *node, HNode *key)
{
    return node == key;
}

static void process_timers()
{
    uint64_t now_ms = get_monotonic_msec();
    // idle timers using a linked list
    while (!dlist_empty(&g_data.idle_list))
    {
        Conn *conn = container_of(g_data.idle_list.next, Conn, idle_node);
        uint64_t next_ms = conn->last_active_ms + k_idle_timeout_ms;
        if (next_ms >= now_ms)
        {
            break; // not expired
        }

        conn_destroy(conn);
    }
    // TTL timers using a heap
    const size_t k_max_works = 2000;
    size_t nworks = 0;
    const std::vector<HeapItem> &heap = g_data.heap;
    while (!heap.empty() && heap[0].val < now_ms)
    {
        Entry *ent = container_of(heap[0].ref, Entry, heap_idx);
        HNode *node = hm_delete(&g_data.db, &ent->node, &hnode_same);
        assert(node == &ent->node);
        // delete the key
        entry_del(ent);
        if (nworks++ >= k_max_works)
        {
            // don't stall the server if too many keys are expiring at once
            break;
        }
    }
}


int main()
{
    // initialization
    WSADATA wsa;
    if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0)
    {
        die("WSAStartup failed");
    }

    dlist_init(&g_data.idle_list);
    thread_pool_init(&g_data.thread_pool, 4);

    // the listening socket
    SOCKET fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd == INVALID_SOCKET)
    {
        die("socket()");
    }
    int val = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, (const char *)&val, sizeof(val));

    // bind
    struct sockaddr_in addr = {};
    addr.sin_family = AF_INET;
    addr.sin_port = ntohs(6379);
    addr.sin_addr.s_addr = ntohl(0); // wildcard address 0.0.0.0
    int rv = bind(fd, (const sockaddr *)&addr, sizeof(addr));
    if (rv)
    {
        die("bind()");
    }

    // set the listen fd to nonblocking mode
    fd_set_nb(fd);

    // listen
    rv = listen(fd, SOMAXCONN);
    if (rv)
    {
        die("listen()");
    }

    // the event loop
    while (true)
    {
        // prepare the arguments of the select()
        fd_set read_fds, write_fds, except_fds;
        FD_ZERO(&read_fds);
        FD_ZERO(&write_fds);
        FD_ZERO(&except_fds);

        // put the listening socket in read set
        FD_SET(fd, &read_fds);
        FD_SET(fd, &except_fds);

        // the rest are connection sockets
        for (Conn *conn : g_data.fd2conn)
        {
            if (!conn)
            {
                continue;
            }
            // always select() for error
            FD_SET(conn->fd, &except_fds);
            // select() flags from the application's intent
            if (conn->want_read)
            {
                FD_SET(conn->fd, &read_fds);
            }
            if (conn->want_write)
            {
                FD_SET(conn->fd, &write_fds);
            }
        }

        // wait for readiness
        int32_t timeout_ms = next_timer_ms();
        struct timeval tv;
        if (timeout_ms < 0)
        {
            tv.tv_sec = -1;
            tv.tv_usec = 0;
        }
        else
        {
            tv.tv_sec = timeout_ms / 1000;
            tv.tv_usec = (timeout_ms % 1000) * 1000;
        }

        int rv = select(0, &read_fds, &write_fds, &except_fds, timeout_ms < 0 ? NULL : &tv);
        if (rv < 0 && WSAGetLastError() == WSAEINTR)
        {
            continue; // not an error
        }
        if (rv < 0)
        {
            die("select");
        }

        // handle the listening socket
        if (FD_ISSET(fd, &read_fds))
        {
            handle_accept(fd);
        }

        // handle connection sockets
        for (Conn *conn : g_data.fd2conn)
        {
            if (!conn)
            {
                continue;
            }

            // update the idle timer by moving conn to the end of the list
            conn->last_active_ms = get_monotonic_msec();
            dlist_detach(&conn->idle_node);
            dlist_insert_before(&g_data.idle_list, &conn->idle_node);

            // handle IO
            if (FD_ISSET(conn->fd, &read_fds))
            {
                handle_read(conn); // application logic
            }
            if (FD_ISSET(conn->fd, &write_fds))
            {
                handle_write(conn); // application logic
            }

            // close the socket from socket error or application logic
            if (FD_ISSET(conn->fd, &except_fds) || conn->want_close)
            {
                conn_destroy(conn);
            }
        } // for each connection sockets

        // handle timers
        process_timers();

        // check for shutdown request
        if (g_data.shutdown_requested)
        {
            printf("Shutdown requested by client. Closing server...\n");
            break;
        }
    } // the event loop
    WSACleanup();

    return 0;
}
